export { default as Dialogs } from './Dialogs/Dialogs'
export { default as Header } from './Header/Header'
export { default as Login } from './Login/login'
export { default as Music } from './Music/Music'
export { default as Navbar } from './Navbar/Navbar'
export { default as News } from './News/News'
export { Profile } from './Profile/Profile'
export { ProfileEdit } from './ProfileEdit/ProfileEdit'
export { default as Settings } from './Settings/Settings'
export { default as Users } from './Users/Users'